import { readFileSync, writeFileSync } from 'node:fs';

const frontendPath = new URL('../script/data/words.json', import.meta.url);
const backendPath = new URL('../../lettering-backend/data/english/words.json', import.meta.url);
const data = JSON.parse(readFileSync(frontendPath, 'utf8'));

const source = `
ABILITY|habilidade|habilidad
ACTION|ação|acción
AGE|idade|edad
AIR|ar|aire
ANGER|raiva|ira
ANSWER|resposta|respuesta
AREA|área|área
ART|arte|arte
ATTENTION|atenção|atención
BEAUTY|beleza|belleza
BEGINNING|começo|comienzo
BEHAVIOR|comportamento|comportamiento
BELIEF|crença|creencia
BIRTH|nascimento|nacimiento
BUSINESS|negócio|negocio
CARE|cuidado|cuidado
CAUSE|causa|causa
CHANCE|chance|oportunidad
CHANGE|mudança|cambio
CHOICE|escolha|elección
COMMUNITY|comunidade|comunidad
COMPANY|empresa|empresa
COURAGE|coragem|coraje
CULTURE|cultura|cultura
DANGER|perigo|peligro
DAY|dia|día
DEATH|morte|muerte
DECISION|decisão|decisión
DESIRE|desejo|deseo
DEVELOPMENT|desenvolvimento|desarrollo
DIFFERENCE|diferença|diferencia
DIFFICULTY|dificuldade|dificultad
DIRECTION|direção|dirección
DISCOVERY|descoberta|descubrimiento
DOUBT|dúvida|duda
DREAM|sonho|sueño
EARTH|terra|tierra
EDUCATION|educação|educación
EFFECT|efeito|efecto
EFFORT|esforço|esfuerzo
ENERGY|energia|energía
ENVIRONMENT|meio ambiente|medio ambiente
ERROR|erro|error
EVENT|evento|evento
EXAMPLE|exemplo|ejemplo
EXPERIENCE|experiência|experiencia
FACT|fato|hecho
FAITH|fé|fe
FEAR|medo|miedo
FEELING|sentimento|sentimiento
FIRE|fogo|fuego
FREEDOM|liberdade|libertad
FRIENDSHIP|amizade|amistad
FUTURE|futuro|futuro
GROWTH|crescimento|crecimiento
HAPPINESS|felicidade|felicidad
HARM|dano|daño
HATE|ódio|odio
HEALTH|saúde|salud
HELP|ajuda|ayuda
HISTORY|história|historia
HOPE|esperança|esperanza
IDEA|ideia|idea
IMPORTANCE|importância|importancia
INFORMATION|informação|información
INTEREST|interesse|interés
KNOWLEDGE|conhecimento|conocimiento
LANGUAGE|idioma|idioma
LAW|lei|ley
LEVEL|nível|nivel
LIFE|vida|vida
LIGHT|luz|luz
LOVE|amor|amor
LUCK|sorte|suerte
MEANING|significado|significado
MEMORY|memória|memoria
MIND|mente|mente
MISTAKE|erro|error
MONEY|dinheiro|dinero
MONTH|mês|mes
MUSIC|música|música
NAME|nome|nombre
NATURE|natureza|naturaleza
NEED|necessidade|necesidad
NEWS|notícia|noticia
NIGHT|noite|noche
NUMBER|número|número
OPINION|opinião|opinión
OPPORTUNITY|oportunidade|oportunidad
ORDER|ordem|orden
PAIN|dor|dolor
PEACE|paz|paz
PLACE|lugar|lugar
PLAN|plano|plan
PLEASURE|prazer|placer
POINT|ponto|punto
POWER|poder|poder
PROBLEM|problema|problema
PROGRESS|progresso|progreso
PURPOSE|propósito|propósito
QUESTION|pergunta|pregunta
REASON|razão|razón
RELATIONSHIP|relacionamento|relación
RESPECT|respeito|respeto
RESULT|resultado|resultado
RISK|risco|riesgo
SAFETY|segurança|seguridad
SCIENCE|ciência|ciencia
SECRET|segredo|secreto
SENSE|sentido|sentido
SOCIETY|sociedade|sociedad
SPACE|espaço|espacio
STORY|história|historia
STRENGTH|força|fuerza
SUCCESS|sucesso|éxito
SYSTEM|sistema|sistema
TIME|tempo|tiempo
TRUTH|verdade|verdad
VALUE|valor|valor
VICTORY|vitória|victoria
VOICE|voz|voz
WAR|guerra|guerra
WATER|água|agua
WAY|caminho|manera
WEEK|semana|semana
WORK|trabalho|trabajo
WORLD|mundo|mundo
YEAR|ano|año
ADULT|adulto|adulto
BABY|bebê|bebé
BOY|menino|niño
BROTHER|irmão|hermano
CHILD|criança|niño
COUPLE|casal|pareja
DAUGHTER|filha|hija
FAMILY|família|familia
FATHER|pai|padre
FRIEND|amigo|amigo
GIRL|menina|niña
GROUP|grupo|grupo
GUEST|convidado|invitado
HERO|herói|héroe
HUMAN|ser humano|humano
HUSBAND|marido|esposo
LEADER|líder|líder
MAN|homem|hombre
MEMBER|membro|miembro
MOTHER|mãe|madre
NEIGHBOR|vizinho|vecino
PARENT|pai ou mãe|padre o madre
PARTNER|parceiro|pareja
PEOPLE|pessoas|personas
PERSON|pessoa|persona
SISTER|irmã|hermana
SON|filho|hijo
STUDENT|estudante|estudiante
TEAM|equipe|equipo
WIFE|esposa|esposa
WOMAN|mulher|mujer
BEACH|praia|playa
CITY|cidade|ciudad
COUNTRY|país|país
DESERT|deserto|desierto
FIELD|campo|campo
FOREST|floresta|bosque
GARDEN|jardim|jardín
HILL|colina|colina
HOME|lar|hogar
ISLAND|ilha|isla
LAKE|lago|lago
LAND|terra|tierra
MOUNTAIN|montanha|montaña
OCEAN|oceano|océano
PARK|parque|parque
RIVER|rio|río
ROAD|estrada|carretera
SEA|mar|mar
SKY|céu|cielo
STREET|rua|calle
SUN|sol|sol
TOWN|cidade pequena|pueblo
VALLEY|vale|valle
VILLAGE|vila|aldea
WEATHER|clima|clima
WIND|vento|viento
AUTUMN|outono|otoño
CLOUD|nuvem|nube
FLOOD|enchente|inundación
ICE|gelo|hielo
MOON|lua|luna
RAIN|chuva|lluvia
SEASON|estação|estación
SNOW|neve|nieve
SPRING|primavera|primavera
STAR|estrela|estrella
STORM|tempestade|tormenta
SUMMER|verão|verano
WINTER|inverno|invierno
COLOR|cor|color
GAME|jogo|juego
MOVIE|filme|película
POEM|poema|poema
SONG|canção|canción
SOUND|som|sonido
SPORT|esporte|deporte
STYLE|estilo|estilo
THEATER|teatro|teatro
ADVICE|conselho|consejo
AGREEMENT|acordo|acuerdo
ARGUMENT|discussão|discusión
CONVERSATION|conversa|conversación
MESSAGE|mensagem|mensaje
PROMISE|promessa|promesa
REPLY|resposta|respuesta
REQUEST|pedido|solicitud
WARNING|aviso|advertencia
ACCOUNT|conta|cuenta
COST|custo|costo
DEBT|dívida|deuda
PRICE|preço|precio
SALE|venda|venta
SERVICE|serviço|servicio
TRADE|comércio|comercio
AMOUNT|quantidade|cantidad
PART|parte|parte
PIECE|peça|pieza
QUALITY|qualidade|calidad
SHAPE|forma|forma
SIZE|tamanho|tamaño
TYPE|tipo|tipo
WEIGHT|peso|peso
ACCESS|acesso|acceso
ACCIDENT|acidente|accidente
ACTIVITY|atividade|actividad
ADDRESS|endereço|dirección
ADVANTAGE|vantagem|ventaja
ADVENTURE|aventura|aventura
AFTERNOON|tarde|tarde
AGENCY|agência|agencia
ANALYSIS|análise|análisis
ANIMAL|animal|animal
APPEARANCE|aparência|apariencia
APPLICATION|aplicação|aplicación
APPROACH|abordagem|enfoque
ARM|braço|brazo
ARRIVAL|chegada|llegada
ARTICLE|artigo|artículo
ASSISTANCE|assistência|asistencia
AUTHOR|autor|autor
BACKGROUND|contexto|fondo
BALANCE|equilíbrio|equilibrio
BANK|banco|banco
BASE|base|base
BATTLE|batalha|batalla
BLOOD|sangue|sangre
BODY|corpo|cuerpo
BONE|osso|hueso
BRAIN|cérebro|cerebro
BRANCH|galho|rama
BREAKFAST|café da manhã|desayuno
BREATH|respiração|respiración
BUILDING|prédio|edificio
CAPITAL|capital|capital
CAREER|carreira|carrera
CATEGORY|categoria|categoría
CELL|célula|célula
CENTER|centro|centro
CENTURY|século|siglo
CHALLENGE|desafio|desafío
CHARACTER|personagem|personaje
CHURCH|igreja|iglesia
CLASS|aula|clase
COLLEGE|faculdade|universidad
COMBINATION|combinação|combinación
COMMUNICATION|comunicação|comunicación
COMPETITION|competição|competencia
CONDITION|condição|condición
CONNECTION|conexão|conexión
CONSTRUCTION|construção|construcción
CONTACT|contato|contacto
CONTENT|conteúdo|contenido
CONTROL|controle|control
CORNER|canto|esquina
CREATION|criação|creación
CROWD|multidão|multitud
CUSTOMER|cliente|cliente
DATA|dados|datos
DAWN|amanhecer|amanecer
DECADE|década|década
DELIVERY|entrega|entrega
DEPARTMENT|departamento|departamento
DESIGN|design|diseño
DETAIL|detalhe|detalle
DINNER|jantar|cena
DISEASE|doença|enfermedad
DISTANCE|distância|distancia
DOCTOR|médico|médico
ECONOMY|economia|economía
EDGE|borda|borde
EMPLOYEE|funcionário|empleado
EMPLOYER|empregador|empleador
ENGINE|motor|motor
ENTERTAINMENT|entretenimento|entretenimiento
ENTRANCE|entrada|entrada
EVENING|fim de tarde|tarde
EXERCISE|exercício|ejercicio
EXIT|saída|salida
EYE|olho|ojo
FACE|rosto|cara
FAILURE|fracasso|fracaso
FARM|fazenda|granja
FASHION|moda|moda
FEATURE|característica|característica
FINGER|dedo|dedo
FLIGHT|voo|vuelo
FLOWER|flor|flor
FOOD|comida|comida
FOOT|pé|pie
FORM|forma|forma
GOAL|objetivo|objetivo
GOVERNMENT|governo|gobierno
GROUND|chão|suelo
HAIR|cabelo|cabello
HAND|mão|mano
HEAD|cabeça|cabeza
HEART|coração|corazón
HEIGHT|altura|altura
HOSPITAL|hospital|hospital
HOTEL|hotel|hotel
HOUR|hora|hora
IMAGE|imagem|imagen
INDUSTRY|indústria|industria
INTERNET|internet|internet
INTERVIEW|entrevista|entrevista
ISSUE|questão|asunto
JOB|emprego|empleo
JOURNEY|jornada|viaje
JUDGE|juiz|juez
KEY|chave|clave
KITCHEN|cozinha|cocina
LEG|perna|pierna
LESSON|lição|lección
LETTER|letra|letra
LOCATION|localização|ubicación
LOSS|perda|pérdida
LUNCH|almoço|almuerzo
MACHINE|máquina|máquina
MANAGER|gerente|gerente
MARKET|mercado|mercado
MATERIAL|material|material
MEAL|refeição|comida
MEASURE|medida|medida
METHOD|método|método
MINUTE|minuto|minuto
MOMENT|momento|momento
MORNING|manhã|mañana
MOUTH|boca|boca
MOVEMENT|movimento|movimiento
NETWORK|rede|red
NOSE|nariz|nariz
NOTE|nota|nota
OFFICE|escritório|oficina
OPTION|opção|opción
ORGANIZATION|organização|organización
PAGE|página|página
PARTY|festa|fiesta
PATIENT|paciente|paciente
PATTERN|padrão|patrón
PERFORMANCE|desempenho|rendimiento
PERIOD|período|período
PICTURE|imagem|imagen
POSITION|posição|posición
PRACTICE|prática|práctica
PRESSURE|pressão|presión
PROCESS|processo|proceso
PRODUCT|produto|producto
PROJECT|projeto|proyecto
PROPERTY|propriedade|propiedad
RESEARCH|pesquisa|investigación
RESOURCE|recurso|recurso
RESPONSE|resposta|respuesta
ROLE|papel|rol
ROOM|quarto|habitación
RULE|regra|regla
SCHOOL|escola|escuela
SECTION|seção|sección
SITUATION|situação|situación
SKILL|habilidade|habilidad
SOLUTION|solução|solución
SOURCE|fonte|fuente
SPEECH|discurso|discurso
STEP|passo|paso
SURFACE|superfície|superficie
TASK|tarefa|tarea
TEACHER|professor|profesor
TECHNOLOGY|tecnologia|tecnología
TEMPERATURE|temperatura|temperatura
TEST|teste|prueba
THEORY|teoria|teoría
THING|coisa|cosa
THOUGHT|pensamento|pensamiento
TOUR|passeio|recorrido
TRADITION|tradição|tradición
TRAINING|treinamento|entrenamiento
TRANSPORT|transporte|transporte
TRAVEL|viagem|viaje
UNIVERSITY|universidade|universidad
USER|usuário|usuario
VARIETY|variedade|variedad
VERSION|versão|versión
VIEW|vista|vista
VISIT|visita|visita
WALL|parede|pared
WORD|palavra|palabra
WRITING|escrita|escritura
`.trim();

const words = source.split('\n').map(line => {
    const [word, portuguese, spanish] = line.split('|');
    return { word, translations: { 'pt-BR': [portuguese], 'es-ES': [spanish] }, score: word.length * 10 };
}).sort((a, b) => a.word.localeCompare(b.word, 'en'));
const duplicates = words.filter((entry, index) => index && entry.word === words[index - 1].word);
if (duplicates.length) throw new Error(`Duplicate nouns: ${duplicates.map(entry => entry.word).join(', ')}`);
if (words.length < 200) throw new Error(`Expected at least 200 nouns, found ${words.length}`);
data.general.nouns = { words };
const output = `${JSON.stringify(data, null, 2)}\n`;
writeFileSync(frontendPath, output);
writeFileSync(backendPath, output);
console.log(`Wrote ${words.length} nouns from ${words[0].word} to ${words.at(-1).word}.`);
