import { readFileSync, writeFileSync } from 'node:fs';

const frontendPath = new URL('../script/data/words.json', import.meta.url);
const backendPath = new URL('../../lettering-backend/data/english/words.json', import.meta.url);

const additions = [
    ['AARDVARK', 'porco-da-terra', 'cerdo hormiguero'],
    ['ALBATROSS', 'albatroz', 'albatros'],
    ['ALLIGATOR', 'aligátor', 'aligátor'],
    ['ANGELFISH', 'peixe-anjo', 'pez ángel'],
    ['ANGLERFISH', 'peixe-pescador', 'rape abisal'],
    ['ANTELOPE', 'antílope', 'antílope'],
    ['APE', 'símio', 'simio'],
    ['AUK', 'alca', 'alca'],
    ['AXOLOTL', 'axolote', 'ajolote'],
    ['BANDICOOT', 'bandicoot', 'bandicut'],
    ['BARNACLE', 'craca', 'percebe'],
    ['BARRACUDA', 'barracuda', 'barracuda'],
    ['BASILISK', 'basilisco', 'basilisco'],
    ['BINTURONG', 'binturongue', 'binturong'],
    ['BITTERN', 'abetouro', 'avetoro'],
    ['BLACKBIRD', 'melro', 'mirlo'],
    ['BLOWFISH', 'baiacu', 'pez globo'],
    ['BLUEBIRD', 'azulão', 'azulejo'],
    ['BOAR', 'javali', 'jabalí'],
    ['BOBCAT', 'lince-vermelho', 'lince rojo'],
    ['BONOBO', 'bonobo', 'bonobo'],
    ['BOWERBIRD', 'pássaro-jardineiro', 'pájaro jardinero'],
    ['BULLFINCH', 'dom-fafe', 'camachuelo'],
    ['BUMBLEBEE', 'mamangava', 'abejorro'],
    ['BUTTERFLY', 'borboleta', 'mariposa diurna'],
    ['CAPYBARA', 'capivara', 'carpincho'],
    ['CARACAL', 'caracal', 'caracal'],
    ['CARIBOU', 'caribu', 'caribú'],
    ['CARP', 'carpa', 'carpa'],
    ['CASSOWARY', 'casuar', 'casuario'],
    ['CATERPILLAR', 'lagarta', 'oruga'],
    ['CENTIPEDE', 'centopeia', 'ciempiés'],
    ['CHAMELEON', 'camaleão', 'camaleón'],
    ['CHINCHILLA', 'chinchila', 'chinchilla'],
    ['CICADA', 'cigarra', 'cigarra'],
    ['COATI', 'quati', 'coatí'],
    ['COBRA', 'naja', 'cobra'],
    ['COCKATOO', 'cacatua', 'cacatúa'],
    ['COCKROACH', 'barata', 'cucaracha'],
    ['COD', 'bacalhau', 'bacalao'],
    ['COUGAR', 'onça-parda', 'puma'],
    ['COYOTE', 'coiote', 'coyote'],
    ['CRANE', 'grou', 'grulla'],
    ['CRICKET', 'grilo', 'grillo'],
    ['CROCODILE', 'crocodilo', 'cocodrilo'],
    ['CROW', 'corvo', 'cuervo'],
    ['CUTTLEFISH', 'sépia', 'sepia'],
    ['DAMSELFLY', 'donzelinha', 'caballito del diablo'],
    ['DORMOUSE', 'arganaz', 'lirón'],
    ['DOVE', 'pomba', 'paloma'],
    ['DRAGONFLY', 'libélula', 'libélula'],
    ['DUGONG', 'dugongo', 'dugongo'],
    ['EARWIG', 'tesourinha', 'tijereta'],
    ['ECHIDNA', 'equidna', 'equidna'],
    ['EEL', 'enguia', 'anguila'],
    ['EGRET', 'garça-branca', 'garceta'],
    ['ELEPHANT', 'elefante', 'elefante'],
    ['ELK', 'uapiti', 'uapití'],
    ['FINCH', 'tentilhão', 'pinzón'],
    ['FIREFLY', 'vaga-lume', 'luciérnaga'],
    ['FLATWORM', 'platelminto', 'gusano plano'],
    ['GALAGO', 'gálago', 'gálago'],
    ['GAR', 'peixe-jacaré', 'pez lagarto'],
    ['GIBBON', 'gibão', 'gibón'],
    ['GLOWWORM', 'pirilampo', 'gusano luminoso'],
    ['GOLDFISH', 'peixe-dourado', 'pez dorado'],
    ['GORILLA', 'gorila', 'gorila'],
    ['GRASSHOPPER', 'gafanhoto', 'saltamontes'],
    ['GROUNDHOG', 'marmota-americana', 'marmota americana'],
    ['GROUPER', 'garoupa', 'mero'],
    ['GUINEAPIG', 'porquinho-da-índia', 'cobaya'],
    ['GULL', 'gaivota', 'gaviota'],
    ['HADDOCK', 'eglefino', 'eglefino'],
    ['HAGFISH', 'peixe-bruxa', 'mixino'],
    ['HARE', 'lebre', 'liebre'],
    ['HERRING', 'arenque', 'arenque'],
    ['HORNET', 'vespão', 'avispón'],
    ['HORSESHOECRAB', 'caranguejo-ferradura', 'cangrejo herradura'],
    ['HUMMINGBIRD', 'beija-flor', 'colibrí'],
    ['IBEX', 'íbex', 'íbice'],
    ['IBIS', 'íbis', 'ibis'],
    ['JELLYFISH', 'água-viva', 'medusa'],
    ['JERBOA', 'jerboa', 'jerbo'],
    ['KAKAPO', 'kakapo', 'kakapo'],
    ['KANGAROO', 'canguru', 'canguro'],
    ['KESTREL', 'peneireiro', 'cernícalo'],
    ['KINGFISHER', 'martim-pescador', 'martín pescador'],
    ['KIWI', 'kiwi', 'kiwi'],
    ['KOALA', 'coala', 'koala'],
    ['KOMODODRAGON', 'dragão-de-komodo', 'dragón de Komodo'],
    ['LEECH', 'sanguessuga', 'sanguijuela'],
    ['LOCUST', 'gafanhoto-migratório', 'langosta'],
    ['LORIS', 'lóris', 'loris'],
    ['LOUSE', 'piolho', 'piojo'],
    ['MACAW', 'arara', 'guacamayo'],
    ['MACKEREL', 'cavala', 'caballa'],
    ['MAGPIE', 'pega', 'urraca'],
    ['MALLARD', 'pato-real', 'ánade real'],
    ['MAMMOTH', 'mamute', 'mamut'],
    ['MANATEE', 'peixe-boi', 'manatí'],
    ['MANDRILL', 'mandril', 'mandril'],
    ['MANTA', 'jamanta', 'mantarraya'],
    ['MANTIS', 'louva-a-deus', 'mantis religiosa'],
    ['MARLIN', 'marlim', 'marlín'],
    ['MARMOT', 'marmota', 'marmota'],
    ['MILLIPEDE', 'milípede', 'milpiés'],
    ['MINNOW', 'peixinho', 'piscardo'],
    ['MONGOOSE', 'mangusto', 'mangosta'],
    ['MONKFISH', 'tamboril', 'rape'],
    ['MUSSEL', 'mexilhão', 'mejillón'],
    ['NARWHAL', 'narval', 'narval'],
    ['NAUTILUS', 'náutilo', 'nautilo'],
    ['NIGHTINGALE', 'rouxinol', 'ruiseñor'],
    ['OKAPI', 'ocapi', 'okapi'],
    ['OPOSSUM', 'gambá', 'zarigüeya'],
    ['ORANGUTAN', 'orangotango', 'orangután'],
    ['OX', 'boi', 'buey'],
    ['PANGOLIN', 'pangolim', 'pangolín'],
    ['PANTHER', 'pantera', 'pantera'],
    ['PARTRIDGE', 'perdiz', 'perdiz'],
    ['PECCARY', 'cateto', 'pecarí'],
    ['PLATYPUS', 'ornitorrinco', 'ornitorrinco'],
    ['POLECAT', 'doninha-fedorenta', 'turón'],
    ['PORPOISE', 'toninha', 'marsopa'],
    ['PRAWN', 'camarão', 'langostino'],
    ['PUFFIN', 'papagaio-do-mar', 'frailecillo'],
    ['PUMA', 'puma', 'puma'],
    ['PYTHON', 'píton', 'pitón'],
    ['QUAIL', 'codorna', 'codorniz'],
    ['QUETZAL', 'quetzal', 'quetzal'],
    ['RATTLESNAKE', 'cascavel', 'serpiente de cascabel'],
    ['RAVEN', 'corvo-grande', 'cuervo grande'],
    ['REINDEER', 'rena', 'reno'],
    ['RHEA', 'ema', 'ñandú'],
    ['ROBIN', 'pisco-de-peito-ruivo', 'petirrojo'],
    ['SALAMANDER', 'salamandra', 'salamandra'],
    ['SALMON', 'salmão', 'salmón'],
    ['SARDINE', 'sardinha', 'sardina'],
    ['SAWFISH', 'peixe-serra', 'pez sierra'],
    ['SCALLOP', 'vieira', 'vieira'],
    ['SCORPION', 'escorpião', 'escorpión'],
    ['SEAHORSE', 'cavalo-marinho', 'caballito de mar'],
    ['SEAURCHIN', 'ouriço-do-mar', 'erizo de mar'],
    ['SHREW', 'musaranho', 'musaraña'],
    ['SILKWORM', 'bicho-da-seda', 'gusano de seda'],
    ['SILVERFISH', 'traça-dos-livros', 'pececillo de plata'],
    ['SPONGE', 'esponja-do-mar', 'esponja de mar'],
    ['STINGRAY', 'arraia', 'raya'],
    ['STOAT', 'arminho', 'armiño'],
    ['SWORDFISH', 'peixe-espada', 'pez espada'],
    ['TARANTULA', 'tarântula', 'tarántula'],
    ['TERMITE', 'cupim', 'termita'],
    ['THRUSH', 'tordo', 'zorzal'],
    ['TICK', 'carrapato', 'garrapata'],
    ['TROUT', 'truta', 'trucha'],
    ['TUNA', 'atum', 'atún'],
    ['VICUNA', 'vicunha', 'vicuña'],
    ['VIPER', 'víbora', 'víbora'],
    ['VOLE', 'rato-do-campo', 'topillo'],
    ['VULTURE', 'abutre', 'buitre'],
    ['WEASEL', 'doninha', 'comadreja'],
    ['WILDEBEEST', 'gnu', 'ñu'],
    ['WOODLOUSE', 'tatuzinho-de-jardim', 'cochinilla de la humedad'],
    ['WOODPECKER', 'pica-pau', 'pájaro carpintero'],
    ['ZEBU', 'zebu', 'cebú'],
];

const data = JSON.parse(readFileSync(frontendPath, 'utf8'));
const words = new Map(data.general.animals.words.map(entry => [entry.word, entry]));
words.delete('KOMODO');

for (const [word, portuguese, spanish] of additions) {
    if (words.has(word)) continue;
    words.set(word, {
        word,
        translations: { 'pt-BR': [portuguese], 'es-ES': [spanish] },
        score: word.length * 10,
    });
}

const correctedTranslations = {
    ALLIGATOR: { 'pt-BR': ['jacaré'], 'es-ES': ['caimán'] },
    BARNACLE: { 'pt-BR': ['craca'], 'es-ES': ['bálano', 'percebe'] },
    BITTERN: { 'pt-BR': ['socó-boi'], 'es-ES': ['avetoro'] },
    BLUEBIRD: { 'pt-BR': ['pássaro-azul'], 'es-ES': ['azulejo'] },
    BUTTERFLY: { 'pt-BR': ['borboleta'], 'es-ES': ['mariposa'] },
    FROG: { 'pt-BR': ['rã', 'perereca'], 'es-ES': ['rana'] },
    GLOWWORM: { 'pt-BR': ['larva-luminosa'], 'es-ES': ['gusano luminoso'] },
    GOPHER: { 'pt-BR': ['geômio', 'esquilo-da-terra'], 'es-ES': ['tuza'] },
    HAWK: { 'pt-BR': ['gavião'], 'es-ES': ['gavilán'] },
    IBEX: { 'pt-BR': ['íbex', 'cabra-montês'], 'es-ES': ['íbice'] },
    JAGUAR: { 'pt-BR': ['onça-pintada', 'jaguar'], 'es-ES': ['jaguar'] },
    LOCUST: { 'pt-BR': ['gafanhoto-migratório'], 'es-ES': ['langosta migratoria'] },
    MULE: { 'pt-BR': ['mula'], 'es-ES': ['mula'] },
    MOUSE: { 'pt-BR': ['camundongo'], 'es-ES': ['ratón'] },
    PARROT: { 'pt-BR': ['papagaio'], 'es-ES': ['loro', 'papagayo'] },
    POLECAT: { 'pt-BR': ['toirão'], 'es-ES': ['turón'] },
    SILVERFISH: { 'pt-BR': ['peixinho-de-prata', 'traça-dos-livros'], 'es-ES': ['pececillo de plata'] },
    SKUNK: { 'pt-BR': ['cangambá', 'jaritataca'], 'es-ES': ['mofeta', 'zorrillo'] },
    WALLABY: { 'pt-BR': ['wallaby', 'ualabi'], 'es-ES': ['ualabí'] },
    WARTHOG: { 'pt-BR': ['javali-africano', 'facócero'], 'es-ES': ['facóquero'] },
    YAK: { 'pt-BR': ['iaque'], 'es-ES': ['yak', 'yac'] },
};

for (const [word, translations] of Object.entries(correctedTranslations)) {
    const entry = words.get(word);
    if (!entry) throw new Error(`Cannot correct missing animal: ${word}`);
    entry.translations = translations;
}

const sortedWords = [...words.values()].sort((first, second) => first.word.localeCompare(second.word, 'en'));
if (sortedWords.length !== 300) throw new Error(`Expected 300 animals, found ${sortedWords.length}`);

data.general.animals.words = sortedWords;
const output = `${JSON.stringify(data, null, 2)}\n`;
writeFileSync(frontendPath, output);
writeFileSync(backendPath, output);

console.log(`Wrote ${sortedWords.length} animals from ${sortedWords[0].word} to ${sortedWords.at(-1).word}.`);
